name: pokete
summary: A terminal based Pokemon like game
description: |
      Imagine you're a Pokete-Trainer and your goal is it to run around in the world and catch/train as many Poketes as possible and to get the best trainer.

First of all you get a starter Pokete (Steini), that you can use to fight battles with other Poketes. The controls are w a s d to walk around.

When entering the high grass (;), you may be attacked by a wild Pokete. By pressing 1 you can choose between the attacks (as long their AP is over 0) your Pokete has, and by pressing the according number, or navigating with the "*"-cursor to the attack and pressing enter. The wild Pokete will fight back, you can kill it and gain XP to level up your Pokete or you can catch it to have it fight for you. To catch a Pokete you have to first weaken the enemy and then throw a Poketeball. And with a bit luck you can catch it. Pressing the "1" key you can take a look at your current deck, see the detailed information of your Pokete and your attacks or rearrange them. Changes will only be saved by quitting the game using the exit function.

Since you're a Pokete-Trainer, you can also fight against other trainers (the other "a" in the middle of the landscape). He will start a fight with you when you get close enough to him. You can not escape from such a trainer fight, you either have to win, or lose. These trainer fights give double the XP.

When one of your Poketes die, or is too weak, you can heal it by going into the house (Pokete-Center), talk the the person there and choose the healing option. Here you can also take a look at all of your Poketes, and not just the six in your team. The ones marked with an "o" are the ones in your deck.

By pressing "e" you can get into a menu where player name, and later other settings, can be changed.

The red balls all over the map are Poketeballs. You'll need these to catch Poketes. Stepping on such a ball will add it to your inventory.
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  pokete:
    command: ./pokete.py
    plugs: [home, network, network-bind, removable-media]

parts:
  pokete:
    plugin: python
    python-packages:
      -scrap_engine
      -playsound
      -pygobject
    source: https://github.com/lxgr-linux/pokete.git
