#work in progress
#FROM alpine:3.15

RUN apk add \
    python3-dev \
    py3-pip 

RUN python3 -m pip install --user scrap_engine playsound pygobject 

RUN mkdir -p /root/.cache/pokete && \
    ln -s /root/.cache/pokete /data

COPY . .

VOLUME ["/data"]

CMD [ "python", "./pokete.py" ]
